---
# tasks file for bvansomeren.openvpn-freebsd-server

- name: ensure openvpn is installed
  package:
    name: "{{ openvpn_packages }}"
    state: present
  ignore_errors: True
  tags:
  - install

- name: ensure openvpn can be started - FreeBSD
  command: sysrc -f /etc/rc.conf openvpn_enable=YES
  register: sysrc_changed
  changed_when:  "'YES -> YES' not in sysrc_changed.stdout"
  ignore_errors: True
  tags:
  - install
  - init
  when: 'ansible_os_family == "FreeBSD"'

- name: ensure openvpn can be started - Linux
  service:
    name: openvpn
    enabled: True
  when: 'ansible_os_family != "FreeBSD"'
  ignore_errors: True

- name: ensure openvpn config and key folder
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ openvpn_folder }}"
  - "{{ openvpn_key_folder }}"
  - "{{ openvpn_client_folder }}"
  - "{{ openvpn_folder }}/ccd"
  tags:
  - configure

- name: ensure x509 defaults are in place
  copy:
    force: no
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}"
    remote_src: yes
  with_items:
  - src: "{{ openvpn_easyrsa_folder }}/x509-types/ca"
    dest: "{{ openvpn_key_folder }}/ca"
  - src: "{{ openvpn_easyrsa_folder }}/x509-types/client"
    dest: "{{ openvpn_key_folder }}/client"
  - src: "{{ openvpn_easyrsa_folder }}/x509-types/server"
    dest: "{{ openvpn_key_folder }}/server" 
  tags:
  - configure
