---
# tasks file for bvansomeren.openvpn-freebsd-server

- name: ensure OS specifics are included
  include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_os_family }}.yml"
  tags:
  - always

- name: perform install
  include_tasks: install.yml
  tags:
  - install
  - configure

- name: include configuration
  include_tasks: configure.yml
  tags:
  - configure
  - ccd

- name: include server keys
  include_tasks: server-keys.yml
  tags:
  - update_crl

- name: include client key generation
  include_tasks: client-configs.yml
  tags:
  - client
  - pull
  - ccd

- name: include certificate revocation
  include_tasks: revoke.yml
  tags:
  - revoke
